-- Tabla de asistencia de la AA4 (diapositiva final de sesion-aa4-formularios.html)
-- Ejecutar una sola vez en Supabase · SQL Editor · New query · Run

create table if not exists public.asistencia_aa4 (
  id          bigint generated by default as identity primary key,
  creado_at   timestamptz not null default now(),
  nombre      text not null,
  correo      text not null,
  curso       text not null,
  formulario  text,
  equipo      text,
  comentario  text
);

alter table public.asistencia_aa4 enable row level security;

-- Cualquiera que abra la página puede registrar su asistencia…
drop policy if exists "registrar asistencia" on public.asistencia_aa4;
create policy "registrar asistencia"
  on public.asistencia_aa4 for insert to anon with check (true);

-- …pero NADIE puede leer la lista desde la página.
-- La lista se ve solo desde el panel de Supabase (Table editor → asistencia_aa4),
-- porque no se crea ninguna policy de select para el rol anon.

-- Para exportar a Excel: Table editor → asistencia_aa4 → Export → Download as CSV.
